"""
Invoice Engine — ATO-compliant PDF invoice generator.
Ported from backpocket-os/core/invoice_engine.py.
Standalone: reads business config from .env, no external DB deps.
"""

from __future__ import annotations

import os
from datetime import datetime, timedelta
from pathlib import Path

from fpdf import FPDF

INVOICE_DIR = Path("uploads/invoices")
INVOICE_DIR.mkdir(parents=True, exist_ok=True)

GST_RATE = 0.1  # 10% Australian GST


def _biz(key: str, fallback: str = "") -> str:
    return os.getenv(key, fallback)


class InvoicePDF(FPDF):
    """ATO-compliant tax invoice PDF."""

    def header(self):
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(30, 30, 30)
        self.cell(0, 10, "TAX INVOICE", align="R", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, "Australian Goods and Services Tax (GST) Invoice", align="R", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, "Generated by BackPocket OS - Privacy-Native AI for Australian Sole Traders", align="C")


def generate_invoice_pdf(invoice_data: dict, client_data: dict) -> str:
    """
    Generate an ATO-compliant tax invoice PDF.
    Returns the file path of the generated PDF.
    """
    pdf = InvoicePDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # ── Seller block ──────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 7, _biz("BUSINESS_NAME", "Your Business"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    if _biz("BUSINESS_ABN"):
        pdf.cell(0, 5, f"ABN: {_biz('BUSINESS_ABN')}", new_x="LMARGIN", new_y="NEXT")
    if _biz("BUSINESS_EMAIL"):
        pdf.cell(0, 5, _biz("BUSINESS_EMAIL"), new_x="LMARGIN", new_y="NEXT")
    if _biz("BUSINESS_PHONE"):
        pdf.cell(0, 5, _biz("BUSINESS_PHONE"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # ── Invoice metadata ──────────────────────────────────────────────────────
    inv_num  = invoice_data.get("invoice_number", "INV-0001")
    inv_date = invoice_data.get("date", datetime.now().strftime("%Y-%m-%d"))
    due_date = invoice_data.get("due_date", "On receipt")

    col_w  = 90
    start_y = pdf.get_y()

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(col_w, 6, "BILL TO", new_x="RIGHT", new_y="TOP")
    pdf.cell(col_w, 6, "INVOICE DETAILS", new_x="LMARGIN", new_y="NEXT")

    pdf.set_y(start_y + 7)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(col_w, 6, client_data.get("name", "Client"), new_x="RIGHT", new_y="TOP")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(col_w // 2, 6, "Invoice #:", new_x="RIGHT", new_y="TOP")
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(col_w // 2, 6, inv_num, new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 10)
    if client_data.get("email"):
        pdf.cell(col_w, 5, client_data["email"], new_x="RIGHT", new_y="TOP")
    else:
        pdf.cell(col_w, 5, "", new_x="RIGHT", new_y="TOP")
    pdf.cell(col_w // 2, 5, "Date:", new_x="RIGHT", new_y="TOP")
    pdf.cell(col_w // 2, 5, inv_date, new_x="LMARGIN", new_y="NEXT")

    pdf.cell(col_w, 5, "", new_x="RIGHT", new_y="TOP")
    pdf.cell(col_w // 2, 5, "Due Date:", new_x="RIGHT", new_y="TOP")
    pdf.cell(col_w // 2, 5, due_date, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    # ── Line items table ──────────────────────────────────────────────────────
    col_desc, col_qty, col_rate, col_gst, col_amt = 90, 20, 35, 20, 25

    pdf.set_fill_color(45, 45, 45)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(col_desc, 8, "Description", fill=True)
    pdf.cell(col_qty,  8, "Qty",    align="C", fill=True)
    pdf.cell(col_rate, 8, "Rate",   align="R", fill=True)
    pdf.cell(col_gst,  8, "GST",    align="C", fill=True)
    pdf.cell(col_amt,  8, "Amount", align="R", fill=True, new_x="LMARGIN", new_y="NEXT")

    pdf.set_text_color(30, 30, 30)
    pdf.set_font("Helvetica", "", 10)

    line_items = invoice_data.get("line_items", [])
    subtotal = 0.0
    fill = False
    for item in line_items:
        desc         = item.get("description", "Service")
        qty          = float(item.get("qty", item.get("quantity", 1)))
        rate         = float(item.get("rate", item.get("unit_price", 0)))
        includes_gst = item.get("gst", True)
        amount       = qty * rate
        subtotal    += amount

        pdf.set_fill_color(248, 248, 248) if fill else pdf.set_fill_color(255, 255, 255)
        pdf.cell(col_desc, 7, desc[:48],         fill=True)
        pdf.cell(col_qty,  7, str(int(qty)),      align="C", fill=True)
        pdf.cell(col_rate, 7, f"${rate:,.2f}",    align="R", fill=True)
        pdf.cell(col_gst,  7, "Yes" if includes_gst else "No", align="C", fill=True)
        pdf.cell(col_amt,  7, f"${amount:,.2f}",  align="R", fill=True, new_x="LMARGIN", new_y="NEXT")
        fill = not fill

    pdf.ln(2)
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)

    # ── Totals ────────────────────────────────────────────────────────────────
    gst_amount = round(subtotal * GST_RATE / (1 + GST_RATE), 2)
    total      = round(subtotal, 2)
    total_x    = 140

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(30, 30, 30)
    pdf.set_x(total_x)
    pdf.cell(35, 6, "Subtotal (excl. GST):", align="R")
    pdf.cell(25, 6, f"${(subtotal - gst_amount):,.2f}", align="R", new_x="LMARGIN", new_y="NEXT")

    pdf.set_x(total_x)
    pdf.cell(35, 6, f"GST ({int(GST_RATE * 100)}%):", align="R")
    pdf.cell(25, 6, f"${gst_amount:,.2f}", align="R", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "B", 11)
    pdf.set_fill_color(45, 45, 45)
    pdf.set_text_color(255, 255, 255)
    pdf.set_x(total_x)
    pdf.cell(35, 8, "TOTAL (AUD):", align="R", fill=True)
    pdf.cell(25, 8, f"${total:,.2f}", align="R", fill=True, new_x="LMARGIN", new_y="NEXT")

    # ── Notes ─────────────────────────────────────────────────────────────────
    notes = invoice_data.get("notes", "")
    if notes:
        pdf.ln(6)
        pdf.set_text_color(30, 30, 30)
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(0, 5, "Notes:", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(80, 80, 80)
        pdf.multi_cell(0, 5, notes)

    # ── Payment instructions ──────────────────────────────────────────────────
    pdf.ln(4)
    pdf.set_text_color(30, 30, 30)
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(0, 5, "Payment Instructions:", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 5, "Please include invoice number as payment reference.", new_x="LMARGIN", new_y="NEXT")

    # ── Save ──────────────────────────────────────────────────────────────────
    filename  = f"{inv_num.replace('/', '-')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    file_path = str(INVOICE_DIR / filename)
    pdf.output(file_path)
    return file_path


def next_invoice_number() -> str:
    """Generate sequential invoice number based on existing files."""
    existing = sorted(INVOICE_DIR.glob("INV-*.pdf"))
    if not existing:
        return "INV-0001"
    last = existing[-1].stem.split("_")[0]  # e.g. INV-0042
    try:
        num = int(last.split("-")[1]) + 1
    except (IndexError, ValueError):
        num = len(existing) + 1
    return f"INV-{num:04d}"
